[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jumlize"
version = "1.0.0"
dependencies = [
    "spacy",
]

[project.scripts]
jumlize = "main:main"
